name: iOS CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Removing any build lines to avoid the .xcodeproj mismatch
      - name: No iOS build
        run: echo "Skipping iOS build for now."
