name: iOS CI

on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build App
        run: |
          xcodebuild \
            -project myhealth-ios.xcodeproj \
            -scheme myhealth-ios \
            -sdk iphonesimulator \
            build
